[defaults]

# sflow options
sflow2se3-sflow-use-depth-if-available: True
sflow2se3-sflow-use-oflow-if-available: False

sflow2se3-disp-net-archictecture: leaststereo # leaststereo raft

sflow2se3-leaststereo-train-dataset: sceneflow # kitti sceneflow
sflow2se3-raft-train-dataset: sintel # sintel kitti flyingthings3d

sflow2se3-depth-min: 0.01
sflow2se3-depth-max: 15.

# approach options
sflow2se3-pt3d-valid-req-disp-nocc: False

sflow2se3-downscale-factor: 0.08
sflow2se3-downscale-mode: nearest_v2

sflow2se3-depth-complete-invalid: True

# important depth settings: for data-baseline: 0.1
sflow2se3-model-se3-likelihood-disp-abs-std: 3