[defaults]

# sflow options
sflow2se3-sflow-use-depth-if-available: True
sflow2se3-sflow-use-oflow-if-available: False

sflow2se3-disp-net-archictecture: raft # leaststereo raft

sflow2se3-leaststereo-train-dataset: sceneflow # kitti sceneflow
sflow2se3-raft-train-dataset: small # sintel kitti flyingthings3d small

sflow2se3-depth-min: 0.01
sflow2se3-depth-max: 15.

# approach options
sflow2se3-extraction-refinement-cycles: 1
sflow2se3-refinements-per-extraction: 1

sflow2se3-downscale-factor: 0.05

sflow2se3-extraction-cluster-pts-valid-count-max: 100
sflow2se3-rigid-clustering-repetitions: 5 #30 # 1
sflow2se3-model-se3-fit-return-largest-k: 1 #1
sflow2se3-extraction-cluster-types: ["rigid"] # ["rigid", "eucl", "eucl-oflow"]

#sflow2se3-rigid-clustering-method: agglomerative # accumulation | agglomerative | pairs

sflow2se3-depth-complete-invalid: False

# important depth settings: for data-baseline: 0.1
sflow2se3-model-se3-likelihood-disp-abs-std: 3

#sflow2se3-model-euclidean-nn-connect-global-dist-range-ratio-max: 0 # 0.35
