[defaults]

# sflow options
sflow2se3-disp-net-archictecture: leaststereo # leaststereo raft

sflow2se3-leaststereo-train-dataset: sceneflow # kitti sceneflow
sflow2se3-raft-train-dataset: flyingthings3d # sintel kitti flyingthings3d

sflow2se3-depth-min: 0.01
sflow2se3-depth-max: 1000.

# approach options
sflow2se3-pt3d-valid-req-disp-nocc: False

sflow2se3-downscale-factor: 0.05
sflow2se3-downscale-mode: nearest_v2

sflow2se3-se3filter-prob-gain-min: 5 #5
sflow2se3-se3filter-prob-same-mask-max: 0.1


