[defaults]
sflow2se3-approach: raft3d # classic raft3d rigidmask
sflow2se3-raft3d-cluster: False

sflow2se3-pt3d-valid-req-disp-nocc: False
sflow2se3-se3-inlier-req-pt3d-0-valid: True
sflow2se3-pt3d-valid-req-pxl-lower-than: 1.0

sflow2se3-downscale-factor: 0.05
sflow2se3-downscale-mode: nearest_v2
sflow2se3-depth-min: 0.01
sflow2se3-depth-max: 80.
sflow2se3-model-euclidean-nn-pts-count-max: 650

#sflow2se3-disp-fwdbwd-dev-max: 3 # 1
#sflow2se3-disp-fwdbwd-dev-rel-max: 0.05 #0.05
sflow2se3-disp-occl-source: fwdbwd # warp fwdbwd fwdbwd+warp fwdbwd*warp
#sflow2se3-oflow-fwdbwd-dev-max: 3 #1.5
#sflow2se3-oflow-fwdbwd-dev-rel-max: 0.05 #1.5
sflow2se3-oflow-occl-source: fwdbwd # warp fwdbwd fwdbwd+warp fwdbwd*warp
sflow2se3-occl-warp-dssim-max: 0.3

sflow2se3-min-samples: 2
sflow2se3-rigid-dist-dev-max: 0.03 #0.03 #0.05 # 0.05 # Kitti 0.03
sflow2se3-rigid-dist-dev-rel-max: 0.0 #0.02 # Kitti: 0.01
sflow2se3-rigid-dist-max: 999999.0  # 10.0
sflow2se3-rigid-dist-min: -0.05 # 0.1
sflow2se3-rigid-clustering-repetitions: 30 #30 # 1
sflow2se3-rigid-clustering-method: accumulation # accumulation | agglomerative | pairs
sflow2se3-rigid-clustering-accumulation-max-samples: 5 # 5
sflow2se3-rigid-clustering-accumulation-use-range: False
sflow2se3-rigid-clustering-accumulation-largest-k: -1
sflow2se3-rigid-clustering-accumulation-req-neighbor: False # False
#sflow2se3-rigid-clustering-accumulation-linkage: complete
sflow2se3-rigid-clustering-add-sflow-bound: False
sflow2se3-rot-deg-max: 45 # 45

sflow2se3-rigid-clustering-agglomerative-linkage: average # complete average
sflow2se3-rigid-clustering-agglomerative-max-dist: 0.2 #
#sflow2se3-se3fit-dist-dev-max: 0.1 #2 #0.3
#sflow2se3-se3fit-dist-dev-rel-max: 0.

sflow2se3-extraction-cluster-pts-valid-count-max: 100000
sflow2se3-extraction-cluster-types: ["rigid", "eucl-oflow"] # ["rigid", "eucl", "eucl-oflow"]
sflow2se3-extraction-cluster-eucl-min-inlier-perc: 0.70 # 0.5
sflow2se3-extraction-cluster-eucl-oflow-dev-abs-max: 3
sflow2se3-extraction-cluster-eucl-oflow-dev-rel-max: 0.05

sflow2se3-model-se3-fit-return-largest-k: 1 #1

sflow2se3-model-inlier-hard-threshold: 0.0455 # 0.0455

sflow2se3-model-se3-std-factor-occ: 2
sflow2se3-model-se3-disp-std-use-fwdbwd-dev-if-larger: False
sflow2se3-model-se3-oflow-std-use-fwdbwd-dev-if-larger: False

sflow2se3-model-se3-likelihood-use-oflow: True
sflow2se3-model-se3-likelihood-type: exp_dev_larger # pdf, exp_dev_larger
sflow2se3-model-se3-likelihood-oflow-invalid-pairs: -1. # -1. | 0. | 1.
sflow2se3-model-se3-likelihood-oflow-abs-std: 3 #1.5 #3
#sflow2se3-model-se3-likelihood-oflow-rel-std: 0.05 #0.025 #0.025 # 0.05
sflow2se3-model-se3-inlier-oflow-hard-threshold: 0.0455

sflow2se3-model-se3-likelihood-use-disp: True
sflow2se3-model-se3-likelihood-disp-invalid-pairs: 1. # -1. | 0. | 1.
sflow2se3-model-se3-likelihood-disp-abs-std: 3 #3
#sflow2se3-model-se3-likelihood-disp-rel-std: 0.05 #0.025 # 0.05
sflow2se3-model-se3-inlier-disp-hard-threshold: 0.0455

sflow2se3-model-se3-likelihood-use-sflow: False
sflow2se3-model-se3-likelihood-sflow-invalid-pairs: 1.   # -1. | 0. | 1.
sflow2se3-model-se3-likelihood-sflow-abs-std: 1.5
sflow2se3-model-se3-likelihood-sflow-rel-std: 0.025
sflow2se3-model-se3-inlier-sflow-hard-threshold: 0.0455

sflow2se3-oflow-disp-std-auto: True
sflow2se3-oflow-disp-trusted-perc: 0.50
sflow2se3-oflow-disp-std-valid-min-perc: 0.10
#sflow2se3-oflow-disp-std-rel-min: 0.000000 # 0.000000 0.025
#sflow2se3-oflow-disp-std-rel-max: 0.0000001 # 0.0000001 0.10
sflow2se3-oflow-disp-std-abs-min: 2.0
sflow2se3-oflow-disp-std-abs-max: 15 # 6
sflow2se3-oflow-disp-std-correct-truncation: True

#sflow2se3-refinement-pxl-assign-soft: True # True | False
#sflow2se3-refinement-pxl-assign-source: prior*likelihood # prior*likelihood | likelihood

sflow2se3-extraction-refinement-cycles: 1 # 2
sflow2se3-refinements-per-extraction: 1 # 5

sflow2se3-extraction-se3-fit-pt3d-oflow-method: cpu-epnp
sflow2se3-extraction-se3-refine: False
sflow2se3-extraction-se3-refine-pt3d-oflow-method: cpu-iterative-continue #

sflow2se3-extraction-select-objects-source: inlier_soft # inlier_soft inlier_hard
sflow2se3-extraction-split-objects-geo-apply: True
sflow2se3-extraction-split-objects-geo-fuse: True
sflow2se3-refinement-split-objects-geo-fuse-keep-splitted: False
sflow2se3-refinement-split-objects-geo-fuse-req-global-connected: True

sflow2se3-refinement-se3-fit-assign-only-inlier: True
sflow2se3-refinement-se3-fit-assign-hard: True # soft | hard

sflow2se3-refinement-geo-fit-assign-only-inlier: True
sflow2se3-refinement-geo-fit-assign-hard: True # soft | hard

sflow2se3-refinement-se3-fit: False
sflow2se3-refinement-se3-fit-data: pt3d-oflow
sflow2se3-refinement-se3-fit-pt3d-oflow-method: cpu-ransac-epnp
sflow2se3-refinement-se3-refine: True
sflow2se3-refinement-se3-refine-pt3d-oflow-method: cpu-iterative-continue
sflow2se3-refinement-geo-source: se3+geo # se3+geo | se3

sflow2se3-refinement-select-method: greedy # greedy bfs
sflow2se3-refinement-split-objects-geo-apply: False
sflow2se3-refinement-split-objects-geo-fuse: False

sflow2se3-labels-source-argmax: likelihood # prior*inlier | prior*likelihood | likelihood

sflow2se3-assignment-object-method: bayesian # bayesian | upsample

sflow2se3-model-euclidean-nn-dist-inlier-hard-threshold: 0.0455

sflow2se3-model-euclidean-nn-rel-depth-dev-std: 0.12 #0.15 # 0.13
sflow2se3-model-euclidean-nn-uv-dev-rel-to-width-std: 0.08 #0.10 # 0.12


sflow2se3-model-euclidean-nn-connect-global-dist-range-ratio-max: 0.35

sflow2se3-split-objects-geo-method: agglomerative # agglomerative | dbscan

sflow2se3-assign-objects-upsampling-depth-interpolation-apply: False
sflow2se3-assign-objects-upsampling-depth-triangulation-apply: False

sflow2se3-se3filter-prob-gain-min: 3 #5
sflow2se3-se3filter-prob-same-mask-max: 0.5 # 0.1
sflow2se3-se3geofilter-prob-same-mask-max: 0.1 # 0.1

sflow2se3-sim-dist-max: 0.01 #0.2 # 0.1 for sep 0.8
sflow2se3-sim-angle-max: 0.5   # 5 for sep 15

sflow2se3-mask-recall-max: 1.0

sflow2se3-disp-net-archictecture: leaststereo # leaststereo raft

sflow2se3-leaststereo-train-dataset: kitti # kitti sceneflow
sflow2se3-raft-train-dataset: kitti # sintel kitti flyingthings3d

