[defaults]

# sflow options

sflow2se3-disp-net-archictecture: leaststereo # leaststereo raft

sflow2se3-leaststereo-train-dataset: sceneflow # kitti sceneflow
sflow2se3-raft-train-dataset: sintel # sintel kitti flyingthings3d

sflow2se3-depth-min: 0.01
sflow2se3-depth-max: 200. # mountains require this

# approach options
sflow2se3-rigidmask-train-dataset: sceneflow # sceneflow kitti